// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCsRpGBm_sOAhEyexMV7Ght4m01QaJx0Gs',
//     appId: '1:398826641867:web:a6ac15dbada04fa143fe4e',
//     messagingSenderId: '398826641867',
//     projectId: 'projectmanagement-f9264',
//     authDomain: 'projectmanagement-f9264.firebaseapp.com',
//     storageBucket: 'projectmanagement-f9264.appspot.com',
//     measurementId: 'G-2BS4SC4SSN',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBrj992OzOi40OOuIzNhg1PS4D34uAh8Oc',
//     appId: '1:398826641867:android:9f8c3c4220e7f7b443fe4e',
//     messagingSenderId: '398826641867',
//     projectId: 'projectmanagement-f9264',
//     storageBucket: 'projectmanagement-f9264.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCX7cjc3a93XdLslgWCxxbuQQZwxRBrA3U',
//     appId: '1:398826641867:ios:13a6a683c82a437543fe4e',
//     messagingSenderId: '398826641867',
//     projectId: 'projectmanagement-f9264',
//     storageBucket: 'projectmanagement-f9264.appspot.com',
//     iosBundleId: 'com.projectmanagement.ios',
//   );
// }
